sign_in_form_header = "Sign in to Jenkins"
DASHBOARD_TITLE = "Dashboard [Jenkins]"
LOGIN_PAGE_TITLE = "Sign in [Jenkins]"
DASHBOARD_URL = "http://localhost:8080/"
BREADCRUMB_BAR_TEXT = "Dashboard"
LOGOUT_LINK_TEXT = "log out"
