name: Run the tests on pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  run-pytest:
    name: 'run pytest tests'
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run pytest tests
        run: pytest
        env:
          BROWSER_NAME: chrome
          BROWSER_OPTIONS_CHROME: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080
          RUN_CI: true
