name: Run the tests on pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  run-pytest:
    name: 'run pytest tests'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      JENKINS_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      JENKINS_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      JENKINS_HOST: localhost
      JENKINS_PORT: 8080
      BROWSER_NAME: chrome
      BROWSER_OPTIONS_CHROME: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080

    steps:
      - name: git clone
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: set up python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install the code linting and formatting tool Ruff
        run: pip install ruff

      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py312

      - name: prepare jenkins data
        run: |
          cat ${{ github.workspace }}/jenkins_data/jenkins_backup0* > ${{ github.workspace }}/jenkins_backup.tar
          md5sum ${{ github.workspace }}/jenkins_backup.tar

      - name: extract jenkins data and set permission
        run: |
          tar -xvf ./jenkins_backup.tar
          chmod -R 777 ./jenkins_backup/var/jenkins_home
          chmod -R 777 ./.github/

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker start
        run: docker run --rm --detach --name jenkins_ci_container -p 8080:8080 -v ${{ github.workspace }}/jenkins_backup/var/jenkins_home:/var/jenkins_home jenkins/jenkins:2.492.2-lts-jdk17

      - name: Wait for the Jenkins
        run: ./.github/wait-for-jenkins.sh

      - name: check scope of changes
        id: scope_check
        run: ./.github/diff-checker.sh

      - name: pytest run all tests
        if: steps.scope_check.outputs.run_all_tests == 'true'
        run: pytest --alluredir=allure-results

      - name: pytest run picked tests
        if: steps.scope_check.outputs.run_all_tests == 'false'
        run: pytest --alluredir=allure-results

      - name: Ensure gh-pages branch exists
        run: |
          git fetch origin gh-pages || echo "gh-pages does not exist"
          if ! git ls-remote --exit-code origin gh-pages; then
            git checkout --orphan gh-pages
            git commit --allow-empty -m "Init gh-pages"
            git push origin gh-pages
          fi

      - name: Load test report history
        uses: actions/checkout@v4.2.2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true
          allow_empty_commit: true

      - name: Attach screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ github.workspace }}/screenshots
